# Form implementation generated from reading ui file 'd:\ECE4574\Pharmaceutical-Point-of-Sale\checkout.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Checkout(object):
    def setupUi(self, Checkout):
        Checkout.setObjectName("Checkout")
        Checkout.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Checkout)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(25, 51, 381, 451))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(430, 50, 281, 221))
        self.listWidget.setObjectName("listWidget")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(460, 430, 241, 71))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 26, 141, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 20, 81, 31))
        self.label_2.setObjectName("label_2")
        Checkout.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Checkout)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        Checkout.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Checkout)
        self.statusbar.setObjectName("statusbar")
        Checkout.setStatusBar(self.statusbar)

        self.retranslateUi(Checkout)
        self.listWidget.setCurrentRow(-1)
        self.buttonBox.rejected.connect(Checkout.close)
        QtCore.QMetaObject.connectSlotsByName(Checkout)

    def retranslateUi(self, Checkout):
        _translate = QtCore.QCoreApplication.translate
        Checkout.setWindowTitle(_translate("Checkout", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Checkout", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Checkout", "Unit Price"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Checkout", "Amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Checkout", "Total"))
        self.label.setText(_translate("Checkout", "Cart"))
        self.label_2.setText(_translate("Checkout", "Subtotal"))
