# Form implementation generated from reading ui file 'd:\ECE4574\Pharmaceutical-Point-of-Sale\dialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(40, 120, 311, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(43, 90, 311, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_incorrect = QtWidgets.QLabel(Dialog)
        self.label_incorrect.setEnabled(False)
        self.label_incorrect.setGeometry(QtCore.QRect(43, 150, 311, 20))
        self.label_incorrect.setText("")
        self.label_incorrect.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_incorrect.setObjectName("label_incorrect")
        self.OK_button = QtWidgets.QPushButton(Dialog)
        self.OK_button.setGeometry(QtCore.QRect(220, 210, 75, 23))
        self.OK_button.setObjectName("OK_button")
        self.Cancel = QtWidgets.QPushButton(Dialog)
        self.Cancel.setGeometry(QtCore.QRect(310, 210, 75, 23))
        self.Cancel.setObjectName("Cancel")

        self.retranslateUi(Dialog)
        self.Cancel.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Varifacate SSN"))
        self.OK_button.setText(_translate("Dialog", "OK"))
        self.Cancel.setText(_translate("Dialog", "Cancel"))
