# Form implementation generated from reading ui file 'd:\ECE4574\Pharmaceutical-Point-of-Sale\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 676)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 5, 6))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.tabWidget.setObjectName("tabWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 895, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuCheckout = QtWidgets.QMenu(self.menuBar)
        self.menuCheckout.setObjectName("menuCheckout")
        MainWindow.setMenuBar(self.menuBar)
        self.actionCheckout = QtGui.QAction(MainWindow)
        self.actionCheckout.setObjectName("actionCheckout")
        self.actionClear_cart = QtGui.QAction(MainWindow)
        self.actionClear_cart.setObjectName("actionClear_cart")
        self.menuCheckout.addAction(self.actionCheckout)
        self.menuCheckout.addAction(self.actionClear_cart)
        self.menuBar.addAction(self.menuCheckout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuCheckout.setTitle(_translate("MainWindow", "Checkout"))
        self.actionCheckout.setText(_translate("MainWindow", "Checkout"))
        self.actionClear_cart.setText(_translate("MainWindow", "Clear cart"))
