# Form implementation generated from reading ui file 'd:\ECE4574\Pharmaceutical-Point-of-Sale\ssn_check.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ssn_check(object):
    def setupUi(self, ssn_check):
        ssn_check.setObjectName("ssn_check")
        ssn_check.resize(459, 343)
        self.centralwidget = QtWidgets.QWidget(ssn_check)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 220, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 220, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 140, 381, 20))
        self.lineEdit.setObjectName("lineEdit")
        ssn_check.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ssn_check)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 23))
        self.menubar.setObjectName("menubar")
        ssn_check.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ssn_check)
        self.statusbar.setObjectName("statusbar")
        ssn_check.setStatusBar(self.statusbar)

        self.retranslateUi(ssn_check)
        QtCore.QMetaObject.connectSlotsByName(ssn_check)

    def retranslateUi(self, ssn_check):
        _translate = QtCore.QCoreApplication.translate
        ssn_check.setWindowTitle(_translate("ssn_check", "MainWindow"))
        self.pushButton.setText(_translate("ssn_check", "PushButton"))
        self.pushButton_2.setText(_translate("ssn_check", "PushButton"))
